# Project 2: Digit Classification Naive Bayes

**Solution**

# Intro
---
In this project, you'll continue working on your own image recognition system for classifying digits. Read through the code and the instructions carefully and add your own code where indicated. Each problem can be addressed succinctly with the included packages -- please don't add any more. 
As always, you're welcome to work on the project in groups and discuss ideas over Slack, but <b> please prepare your own write-up (with your own code). </b>


## Grading
---
 - Make sure to answer every part in every question.
 - There are 6 questions, each equally weighted and an additional bonus question.
 - The extra credit question will be graded based on your attempts at feature engineering and resulting improved accuracy.
 - Read carefully what is asked including the notes.
 - Additional points may be deducted if:
   - the code is not clean, well commented,
  -  if the functions or answers are too long.

## Requirements:
---
1. Comment your code.
1. All graphs should have titles, label for each axis, and if needed a legend. It should be understandable on its own.
1. All code must run on colab.research.google.com
1. You should not import any additional libraries.
1. Try and minimize the use of the global namespace (meaning keep things in functions).

## Additional Reading and notes
---
If you're interested, check out these links related to digit recognition:

* Yann Lecun's MNIST benchmarks: http://yann.lecun.com/exdb/mnist/
* Stanford Streetview research and data: http://ufldl.stanford.edu/housenumbers/

Finally, if you'd like to get started with Tensorflow, you can read through this tutorial: https://www.tensorflow.org/tutorials/keras/basic_classification. It uses a dataset called "fashion_mnist", which is identical in structure to the original digit mnist, but uses images of clothing rather than images of digits. The number of training examples and number of labels is the same. In fact, you can simply replace the code that loads "fashion_mnist" with "mnist" and everything should work fine.

In [1]:
# This tells matplotlib not to try opening a new window for each plot.
%matplotlib inline

# Import a bunch of libraries.
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
from sklearn.pipeline import Pipeline
from sklearn.datasets import fetch_openml
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Set the randomizer seed so results are the same each time.
np.random.seed(0)

In [ ]:
import sklearn
sklearn.__version__

Load the data. Notice that the data gets partitioned into training, development, and test sets. Also, a small subset of the training data called mini_train_data and mini_train_labels gets defined, which you should use in all the experiments below, unless otherwise noted.

In [2]:
# Load the digit data from https://www.openml.org/d/554 or from default local location '~/scikit_learn_data/...'
X, Y = fetch_openml(name='mnist_784', return_X_y=True, cache=False, as_frame=False)

# Rescale grayscale values to [0,1].
X = X / 255.0

# Shuffle the input: create a random permutation of the integers between 0 and the number of data points and apply this
# permutation to X and Y.
# NOTE: Each time you run this cell, you'll re-shuffle the data, resulting in a different ordering.
shuffle = np.random.permutation(np.arange(X.shape[0]))
X, Y = X[shuffle], Y[shuffle]

print('data shape: ', X.shape)
print('label shape:', Y.shape)

# Set some variables to hold test, dev, and training data.
test_data, test_labels = X[61000:], Y[61000:]
dev_data, dev_labels = X[60000:61000], Y[60000:61000]
train_data, train_labels = X[:60000], Y[:60000]
mini_train_data, mini_train_labels = X[:1000], Y[:1000]

data shape:  (70000, 784)
label shape: (70000,)


### Question 1: Applying a smoothing using numpy.
---

A common image processing technique is to smooth an image by **blurring**. The idea is that the value of a particular pixel is estimated as the weighted combination of the original value and the values around it. Typically, the blurring is Gaussian, i.e., the weight of a pixel's influence is determined by a Gaussian function over the distance to the relevant pixel.

1. Implement a simplified Gaussian blur filter by just using the 8 neighboring pixels like this: the smoothed value of a pixel is a weighted combination of the original value and the 8 neighboring values.
1. Choose some weights as a starting point. Produce and evaluate four 1-Nearest Neighbor models by applying your blur filter in these ways:
  1. Do not use the filter
  1. Filter the training data but not the dev data
  1. Filter the dev data but not the training data
  1. Filter both training data and dev data
1. Show the accuracies of the four models evaluated as described. What do you see? Can you explain why this is?
1. Experiment with weights that makes one model's accuracy at least 0.9.

Notes:
* Train on the (filtered) mini train set.
* Evaluate performance on the (filtered) dev set.
* A good trick to simplify your code is to use numpy's pad function to add 0s around your original array so you don't have to deal with "edge cases".
* In addition, you can use numpy to multiply and sum slices of two arrays.
* [This notebook](https://colab.research.google.com/drive/1eJXTQLtREXQjQIsLOA9uCrBl6B049-pO) might help shows some example numpy code.
* In general, [numpy operations will be much faster than for loops](https://colab.research.google.com/drive/1KJI4JtuIqVdyZHTTe_mAlKYA5XdLFp3_). 
* There are other Guassian blur filters available, for example in `scipy.ndimage.filters`. You are welcome to experiment with those, but in this question, please implement your own.

In [ ]:


def Q1(num_examples=10):

  ### STUDENT START ###   
    fig = plt.figure(figsize=(15,15))
    x=0
    for i in range(num_examples):
        for j in range(num_examples):
            x=x+1
            #get all data matching current digit
            image = mini_train_data[np.where(mini_train_labels==str(i))][j]
            pixels = image.reshape((28, 28))
            x#print(pixels)
            #plot each digit
            ax = fig.add_subplot(num_examples, num_examples, x, xticks=[], yticks=[],xlabel=i)
            #setting the colormap, for example to black and white.
            ax.imshow(pixels, cmap=plt.cm.binary) # cmap='gray'                                
    plt.show()
    
  ### STUDENT END ###

Q1(5)

### Question 2: Modeling your data and experimenting with different Naive Bayes models. 
---

1. Produce two Naive Bayes models and evaluate their performances.  Recall that Naive Bayes estimates P(feature|label), where each label is a categorical, not a real number.
  1. For the first model, map pixel values to either 0 or 1, representing white or black - you should pre-process the data or use `BernoulliNB`'s `binarize` parameter to set the white/black separation threshold to 0.1.  Use `BernoulliNB` to produce the model.
  1. For the second model, map pixel values to either 0, 1, or 2, representing white, gray, or black - you should pre-process the data, seting the white/gray/black separation thresholds to 0.1 and 0.9.  Here you'll likely need to implement a `trianarize` helper function. Since we are going beyond the binary representation of our features, you should use `MultinomialNB` to produce the model.
1. Show the Bernoulli model accuracy and the Multinomial model accuracy.
1. Does the multinomial version improve the results? Why or why not?

Notes:
* Train on the mini train set.
* Evaluate performance on the dev set.



In [12]:
# Solution with binarization by explicit binarize function
def binarize(data, threshold = 0.1):
    binarized_data = np.zeros(data.shape)
    binarized_data[data > threshold] = 1
    binarized_data[data < threshold] = 0
    return binarized_data

def trianarize(data, threshold=[0.1, 0.9]):
    trianarize_data = np.zeros(data.shape) 
    trianarize_data[data <= threshold[0]] = 0
    trianarize_data[(data > threshold[0]) & (data < threshold[1])] = 1
    trianarize_data[data >= threshold[1]] = 2
    return trianarize_data

In [13]:

def Q2():

### STUDENT START ###
    alpha = 1
    binarized_train_data = binarize(mini_train_data) 
    binarized_dev_data = binarize(dev_data) 

    bern = BernoulliNB(alpha=alpha)
    bern.fit(binarized_train_data, mini_train_labels)
    
    #Evaluate performance on the dev set.
    pred = bern.predict(binarized_dev_data)

    #Evaluate performance on the dev set.
    acc = bern.score(binarized_dev_data, dev_labels)
    print('===== Classification report for BernoulliNB =====')
    print(f"BernoulliNB accuracy={acc}")
    print(classification_report(dev_labels,pred))
            
    #For the second model trianarize
    trianarize_train_data = trianarize(mini_train_data) 

    trianarize_dev_data = trianarize(dev_data) 
    mnb = MultinomialNB(alpha=alpha)
    mnb.fit(trianarize_train_data, mini_train_labels)
    
    #Evaluate performance on the dev set.
    predmnb = mnb.predict(trianarize_dev_data)

    #Evaluate performance on the dev set.
    acc = mnb.score(trianarize_dev_data, dev_labels)
    print('===== Classification report for MultinomialNB =====')
    print(f"MultinomialNB accuracy={acc}")
    print(classification_report(dev_labels,predmnb))
### STUDENT END ###
Q2()

===== Classification report for BernoulliNB =====
BernoulliNB accuracy=0.814
              precision    recall  f1-score   support

           0       0.93      0.90      0.91       106
           1       0.88      0.95      0.91       118
           2       0.81      0.72      0.76       106
           3       0.74      0.76      0.75        97
           4       0.76      0.85      0.80        92
           5       0.83      0.68      0.75        88
           6       0.87      0.88      0.88       102
           7       0.88      0.86      0.87       102
           8       0.65      0.72      0.68        94
           9       0.78      0.77      0.77        95

    accuracy                           0.81      1000
   macro avg       0.81      0.81      0.81      1000
weighted avg       0.82      0.81      0.81      1000

===== Classification report for MultinomialNB =====
MultinomialNB accuracy=0.807
              precision    recall  f1-score   support

           0       0.92     

ANSWER:  Does the multinomial version improve the results? Why or why not? TODO

### Question 3: Applying the grid search technique.
1. Search across several values of the LaPlace smoothing parameter (alpha) to find its effect on a Bernoulli Naive Bayes model's performance.  Show the accuracy at each alpha value.
1. What is the best value for alpha? What is the accuracy when alpha is near 0? Is this what you'd expect?

Notes:
* Set binarization threshold to 0.
* Train on the mini train set.
* Evaluate performance by 5-fold cross-validation. 
* Use `GridSearchCV(..., ..., cv=..., scoring='accuracy', iid=False)` to vary alpha and evaluate performance by cross-validation.
* Cross-validation is based on partitions of the training data, so results will be a bit different than if you had used the dev set to evaluate performance.



In [14]:
def Q3(alphas):

### STUDENT START ###
    #Set binarization threshold to 0.
    binarized_train_data = binarize(mini_train_data, 0) 
    binarized_dev_data = binarize(dev_data, 0) 


    #params = []
    #params = params.append(alphas.get("alpha"))
    
    gs = GridSearchCV(estimator = BernoulliNB(),
                      param_grid = alphas,
                      scoring='accuracy',
                      cv=5, verbose = 3)
    
    gs.fit(binarized_train_data, mini_train_labels)
    
    

    #Evaluate performance on the dev set.
    pred = gs.predict(binarized_dev_data)

    #Evaluate performance on the dev set.
    acc = gs.score(binarized_dev_data, dev_labels)
    #print('===== Classification report for BernoulliNB =====')
    print(f"GridSearchCV accuracy={acc}")
    print(classification_report(dev_labels,pred))
    print( "Best Params" + str(gs.best_params_))
    # extract best estimator
    #print(gs.best_estimator_)
### STUDENT END ###

alphas = {'alpha': [1.0e-10, 0.0001, 0.001, 0.01, 0.1, 0.5, 1.0, 2.0, 10.0]}
Q3(alphas)


Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV 1/5] END .......................alpha=1e-10;, score=0.875 total time=   0.0s
[CV 2/5] END .......................alpha=1e-10;, score=0.755 total time=   0.0s
[CV 3/5] END .......................alpha=1e-10;, score=0.840 total time=   0.0s
[CV 4/5] END .......................alpha=1e-10;, score=0.760 total time=   0.0s
[CV 5/5] END .......................alpha=1e-10;, score=0.840 total time=   0.0s
[CV 1/5] END ......................alpha=0.0001;, score=0.860 total time=   0.0s
[CV 2/5] END ......................alpha=0.0001;, score=0.765 total time=   0.0s
[CV 3/5] END ......................alpha=0.0001;, score=0.845 total time=   0.0s
[CV 4/5] END ......................alpha=0.0001;, score=0.785 total time=   0.0s
[CV 5/5] END ......................alpha=0.0001;, score=0.840 total time=   0.0s
[CV 1/5] END .......................alpha=0.001;, score=0.865 total time=   0.0s
[CV 2/5] END .......................alpha=0.001;,

ANSWER: What is the best value for alpha? What is the accuracy when alpha is near 0? Is this what you'd expect?

0 is not smoothing 

### Question 4: Experimenting with Gaussian Naive Bayes
---
1. Produce a model using Guassian Naive Bayes, which is intended for real-valued features, and evaluate performance. You will notice that it does not work so well. 
1. Diagnose and explain the problem.
1. Apply a simple fix so that the model accuracy is around the same as for a Bernoulli Naive Bayes model. 
1. Show the model accuracy before your fix and the model accuracy after your fix.  
1. Explain your solution.

Notes:
* Train on the mini train set.
* Evaluate performance on the dev set.
* Take a look at var_smoothing argument for GaussianNB.
* Feel free to  examine theta and sigma to better understand what's happening. In general though, **it is not a good idea to mess with internal variables of the model**. These are stored in the model's `theta_` and `sigma_` attributes.

In [10]:
#assumes features follow normal distribution
def Q4():

### STUDENT END ###
    gnb = GaussianNB()
    gnb.fit(mini_train_data, mini_train_labels)
    
    #Evaluate performance on the dev set.
    pred = gnb.predict(dev_data)

    #Evaluate performance on the dev set.
    acc = gnb.score(dev_data, dev_labels)
    
    print('===== Classification report for GaussianNB Before Smoothing =====')
    print(f"GaussianNB accuracy={acc}")
    print(classification_report(dev_labels,pred))
    
    gnb = GaussianNB(var_smoothing=.5)
    gnb.fit(mini_train_data, mini_train_labels)    
    #Evaluate performance on the dev set.
    pred = gnb.predict(dev_data)

    #Evaluate performance on the dev set.
    acc = gnb.score(dev_data, dev_labels)
    
    print('===== Classification report for GaussianNB After Smoothing =====')
    print(f"GaussianNB accuracy={acc}")
    print(classification_report(dev_labels,pred))
    
### STUDENT END ###

Q4()

===== Classification report for GaussianNB Before Smoothing =====
GaussianNB accuracy=0.593
              precision    recall  f1-score   support

           0       0.75      0.88      0.81       106
           1       0.87      0.81      0.84       118
           2       0.59      0.44      0.51       106
           3       0.64      0.29      0.40        97
           4       0.78      0.32      0.45        92
           5       0.30      0.67      0.41        88
           6       0.74      0.85      0.79       102
           7       0.92      0.57      0.70       102
           8       0.38      0.11      0.17        94
           9       0.43      0.91      0.58        95

    accuracy                           0.59      1000
   macro avg       0.64      0.58      0.57      1000
weighted avg       0.65      0.59      0.58      1000

===== Classification report for GaussianNB After Smoothing =====
GaussianNB accuracy=0.764
              precision    recall  f1-score   support

   

ANSWER: 1. Explain your solution.

### Question 5: Naive Bayes as a generative model
---
Because Naive Bayes produces a generative model, you can use it to generate digit images.

1. Produce a Bernoulli Naive Bayes model and then use it to generate a 10x10 grid with 10 example images of each digit. Each pixel output will be either 0 or 1: randomly generating a number and then comparing it to the estimated probability of the pixel being either 0 or 1.  Show the grid.
1. How do the generated digit images compare to the training digit images?

Notes:
* You can use np.random.rand() to generate random numbers from a uniform distribution.
* The estimated probability of each pixel being 0 or 1 is stored in the model's `feature_log_prob_` attribute. You can use `np.exp()` to convert a log probability back to a probability.



In [35]:
x = np.random.randint(5, size=(4,10))
y = np.array([1,2,3,4])
clf = MultinomialNB()
nb=clf.fit(x,y)
print(x.shape)
print("="*50)
print(x)
print("="*50)
print(x[2:3])
print("="*50)
print(clf.predict(x[2:3]))
print(nb.feature_log_prob_)

(4, 10)
[[2 1 3 4 0 3 3 4 0 2]
 [2 1 0 3 3 2 3 2 4 2]
 [1 3 1 2 3 1 1 1 1 3]
 [4 3 2 0 4 3 4 2 4 3]]
[[1 3 1 2 3 1 1 1 1 3]]
[3]
[[-2.36712361 -2.77258872 -2.07944154 -1.85629799 -3.4657359  -2.07944154
  -2.07944154 -1.85629799 -3.4657359  -2.36712361]
 [-2.36712361 -2.77258872 -3.4657359  -2.07944154 -2.07944154 -2.36712361
  -2.07944154 -2.36712361 -1.85629799 -2.36712361]
 [-2.60268969 -1.9095425  -2.60268969 -2.19722458 -1.9095425  -2.60268969
  -2.60268969 -2.60268969 -2.60268969 -1.9095425 ]
 [-2.05412373 -2.27726729 -2.56494936 -3.66356165 -2.05412373 -2.27726729
  -2.05412373 -2.56494936 -2.05412373 -2.27726729]]


In [38]:
def plot(examples):
  ### STUDENT START ###   
    fig = plt.figure(figsize=(15,15))
    x=0
    shape = examples.shape()
    row = shape[0]
    coumns =  shape[1]
    for i in range(row):
        for j in range(coumns):
            x=x+1
            #get all data matching current digit
            image = mini_train_data[np.where(mini_train_labels==str(i))][j]
            pixels = image.reshape((28, 28))
            #plot each digit
            ax = fig.add_subplot(num_examples, num_examples, x, xticks=[], yticks=[],xlabel=i)
            #setting the colormap, for example to black and white.
            ax.imshow(pixels, cmap=plt.cm.binary) # cmap='gray'                                
    plt.show()
    
  ### STUDENT END ###



def Q5(num_examples):

### STUDENT START ###

    binarized_train_data = binarize(mini_train_data) 
    binarized_dev_data = binarize(dev_data) 


    bern = BernoulliNB().fit(binarized_train_data, mini_train_labels)
    pred = bern.predict(binarized_dev_data)
    print(pred)
    print(bern.feature_log_prob_)
    #Evaluate performance on the dev set.
   #pred = bern.predict(binarized_dev_data)

### STUDENT END ###

Q5(10)

['8' '4' '1' '9' '6' '6' '3' '7' '9' '0' '4' '3' '1' '1' '3' '7' '1' '1'
 '4' '2' '2' '8' '9' '1' '7' '4' '9' '2' '1' '5' '3' '2' '8' '8' '1' '4'
 '8' '7' '4' '7' '4' '5' '6' '7' '7' '8' '4' '3' '1' '7' '2' '8' '1' '6'
 '2' '7' '1' '7' '9' '1' '7' '4' '0' '5' '0' '7' '1' '9' '8' '3' '7' '0'
 '6' '0' '6' '1' '8' '1' '9' '1' '0' '8' '6' '3' '1' '8' '2' '2' '1' '5'
 '6' '1' '8' '5' '4' '8' '4' '6' '8' '1' '1' '3' '9' '4' '9' '9' '2' '3'
 '0' '5' '2' '8' '8' '6' '9' '0' '5' '0' '3' '5' '2' '0' '4' '6' '7' '1'
 '0' '8' '0' '4' '1' '5' '0' '3' '7' '1' '0' '5' '6' '6' '2' '6' '7' '8'
 '3' '0' '3' '6' '1' '7' '8' '5' '6' '2' '7' '5' '2' '5' '1' '0' '1' '3'
 '2' '4' '9' '5' '1' '1' '1' '9' '5' '8' '1' '3' '8' '1' '2' '8' '5' '0'
 '6' '9' '8' '7' '8' '9' '8' '3' '2' '0' '5' '9' '8' '8' '3' '4' '8' '3'
 '7' '9' '2' '1' '2' '9' '4' '2' '4' '2' '6' '0' '9' '6' '7' '1' '9' '6'
 '7' '6' '7' '1' '0' '8' '0' '5' '3' '7' '0' '3' '8' '6' '0' '7' '9' '3'
 '7' '2' '8' '1' '9' '4' '5' '8' '4' '2' '7' '7' '2

ANSWER: 

### Question 6: Model Calibraiton
---
Recall that:
 * a **strongly calibrated** classifier is rougly 90% accurate when it says it is 90% accurate. The model's estimated posterior probability of the predicted class is indeed 0.9. 
 * A **weakly calibrated** classifier is more accurate when it "says" it is more accurate. The actual accuracy is higher when the model's estimated posterior probability is higher.
 * A **poorly calibrated** classifier has no positive correlation between the model's estimate posterior probability and the actual accuracy.

1. Produce a Bernoulli Naive Bayes model.  
1. Evaluate performance: 
  1. Partition the dev set into several buckets based on the estimated posterior probabilities of the predicted classes (predict_proba)
    - Think of it as a bin in a histogram, where each bin groups a range of estimated posterior probabilities of the predicted classes (predict_proba).
    - Then estimate the actual accuracy the classifier achieved for each bucket. 
    - So, for each prediction:
       - Find the bucket whose range includes the estimated posterior probability, 
       - and update "correct" and "total" counters accordingly. 
       - Show the accuracy for each bucket.
1. How would you characterize the calibration for this Bernoulli Naive Bayes model according to the definitions above?

Notes:
* Set LaPlace smoothing (alpha) to the optimal value (from part 8).
* Set binarization threshold to 0.
* Train on the mini train set.
* Evaluate perfromance on the dev set.



In [ ]:
def Q6(buckets, correct, total):
    
### STUDENT START ###

### STUDENT END ###

buckets = [0.5, 0.9, 0.999, 0.99999, 0.9999999, 0.999999999, 0.99999999999, 0.9999999999999, 1.0]
correct = [0 for i in buckets]
total = [0 for i in buckets]

Q6(buckets, correct, total)

ANSWER: 

### Question 7 EXTRA CREDIT: Feature generation
---
1. Design new features to see if you can produce a Bernoulli Naive Bayes model with better performance.
1. Show the accuracy of a model based on the original features and the accuracy of the model based on the new features.

**Note that improving results is actually hard.**

Here are a few ideas to get you started:
- Try summing or averaging the pixel values in each row.
- Try summing or averaging the pixel values in each column.
- Try summing or averaging the pixel values in each square block. (pick various block sizes)
- Try implementing [*maxpool*](https://computersciencewiki.org/index.php/Max-pooling_/_Pooling) features, taking a rolling maximum over sub-regions of a the image. 
- In any case, you can either transform the original data or add new "features" to it.

Notes:
* Train on the mini train set (enhanced to comprise the new features).
* Evaulate performance on the dev set.
* Ensure that your code is well commented.

In [ ]:
def Q7():

### STUDENT START ###

### STUDENT END ###

Q7()